name: metadraft3
channels:
  - bgoli
  - sbmlteam
  - defaults
dependencies:
  - python=3.7
  - cbmpy
  - sympy
  - biopython
  - xlsxwriter
  - python
  - python-libsbml
  - xlwt
  - pyqt
  - xlrd
  - nose
  - parso
  - tornado
  - openssl
  - prompt_toolkit
  - decorator
  - setuptools
  - certifi
  - pygments

