From ubuntu:latest


RUN apt-get update && apt-get -y install wget git -y gcc build-essential 
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install bioperl -y libparallel-forkmanager-perl -y
RUN apt-get install default-jre -y

RUN git clone https://bitbucket.org/sonnhammergroup/inparanoid.git /inparanoid

RUN wget http://github.com/bbuchfink/diamond/releases/download/v2.0.8/diamond-linux64.tar.gz
RUN tar xzf diamond-linux64.tar.gz

RUN wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.18/blast-2.2.18-x64-linux.tar.gz
RUN tar xvfz blast-2.2.18-x64-linux.tar.gz 

RUN cp ./blast-2.2.18/bin/blastall /inparanoid/
RUN cp ./blast-2.2.18/bin/formatdb /inparanoid/
RUN cp diamond /inparanoid
RUN cp /inparanoid/docker/run.sh .
RUN chmod 755 run.sh
RUN mkdir /input


ENV PATH .:$PATH
ENV LC_ALL C
ENV LANGUAGE C

ENTRYPOINT ["/run.sh"]
